name: fav_books
description: "Flutter Tech Task"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  #network operations∂
  dio: ^5.6.0
  #localizations
  intl: ^0.19.0
  #state management
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  #local storage
  hive: ^2.2.3
  path_provider: ^2.1.4
  dartz: ^0.10.1
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  #notifications
  awesome_notifications: ^0.9.3+1
  cupertino_icons: ^1.0.8
  #svg files
  flutter_svg: ^2.0.9
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  hive_generator: ^2.0.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
